apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
type: Opaque
data:
  slack-url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA1RjlKMENNVTMvQjA1Rk5CVU5IUlAvQTNUdkthbkdkMTdKNmtLb1NIbkNVZWFC