---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  selector: 
    app: alertmanager
  type: LoadBalancer  
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 32093