apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 'opensis-pvc'
  namespace: opensis
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
