apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'opensis'
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: 'opensis'
  namespace: opensis
spec:
  replicas: 1
  selector:
    matchLabels:

      name: 'opensis'
  template:
    metadata:
      labels:
        name: 'opensis'
    spec:
      containers:
      - name: 'opensis'
        image: gladysgodwin/opensis-classic_opensis:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: opensisdb-password
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: opensis-database
          - name: MYSQL_HOSTNAME
            valueFrom:
              secretKeyRef:
                key: opensis-hostname
                name: mysql-secret
        resources:
          limits:
            memory: "1000Mi"
            cpu: "1000m"
          requests:
            cpu: "200m"
            memory: "200Mi"
        ports:
        - containerPort: 5000
        securityContext:
          runAsUser: 33
          runAsGroup: 33
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
        livenessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 5000
          initialDelaySeconds: 180
          periodSeconds: 3
        volumeMounts:
        - name: data-volume
          mountPath: /var/www/html
      volumes:
      - name: 'data-volume'
        persistentVolumeClaim:
          claimName: 'opensis-pvc'
