apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'opensis'
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: 'opensis'
  namespace: opensis
spec:
  replicas: 1
  selector:
    matchLabels:

      name: 'opensis'
  template:
    metadata:
      labels:
        name: 'opensis'
    spec:
      containers:
      - name: 'opensis'
        image: gladysgodwin/theopensis-erp:1.2
        resources:
          limits:
            memory: "1000Mi"
            cpu: "1000m"
          requests:
            cpu: "200m"
            memory: "200Mi"
        ports:
        - containerPort: 5000
        securityContext:
          runAsUser: 1000
          runAsGroup: 3000
          runAsNonRoot: true
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 3
        volumeMounts:
        - name: data-volume
          mountPath: /var/www/html
        - name: data-volume
          mountPath: /var/run/apache2/
      volumes:
      - name: 'data-volume'
        persistentVolumeClaim:
          claimName: 'opensis-pvc'
