apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'opensis'
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: 'opensis'
  namespace: opensis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: 'opensis'
  template:
    metadata:
      labels:
        name: 'opensis'
    spec:
      containers:
      - name: 'opensis'
        image: gladysgodwin/opensis:1.0
        resources:
          limits:
            memory: "800Mi"
            cpu: "600m"
          requests:
            cpu: "200m"
            memory: "200Mi"
        ports:
        - containerPort: 5000
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 3
