apiVersion: v1
kind: PersistentVolume
metadata:
   name: 'opensis-pv'
   namespace: opensis
spec:
  capacity:
     storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  volumeMode: Filesystem
  hostPath:
    path: /opensis/pv-volume
